services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mma
      POSTGRES_PASSWORD: mma
      POSTGRES_DB: mma_prediction
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: